version: '3.8'
services:
  app:
    build: .
    user: node
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    environment:
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_USER_TOKEN=${SLACK_USER_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PERMISSIONS_SHEET_ID=${PERMISSIONS_SHEET_ID}
      - USERS_SHEET_ID=${USERS_SHEET_ID}
    command: npm start
