version: '3.8'
services:
  app:
    build: .
    user: node
    volumes:
      - ./data:/home/node/app/data
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_USER_TOKEN=${SLACK_USER_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: npm run start:prod
